# Generated by Django 6.0.5 on 2026-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contributionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=100),
            preserve_default=False,
        ),
    ]
